# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/scraping.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/scraping.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14proto/scraping.proto\"!\n\x0fScrapingRequest\x12\x0e\n\x06target\x18\x01 \x01(\t\"\'\n\x07WebPage\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"*\n\x10ScrapingResponse\x12\x16\n\x04page\x18\x01 \x01(\x0b\x32\x08.WebPage2<\n\x07Scraper\x12\x31\n\x06scrape\x12\x10.ScrapingRequest\x1a\x11.ScrapingResponse(\x01\x30\x01\x62\x06proto3')
)




_SCRAPINGREQUEST = _descriptor.Descriptor(
  name='ScrapingRequest',
  full_name='ScrapingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='ScrapingRequest.target', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=57,
)


_WEBPAGE = _descriptor.Descriptor(
  name='WebPage',
  full_name='WebPage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='WebPage.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='WebPage.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=98,
)


_SCRAPINGRESPONSE = _descriptor.Descriptor(
  name='ScrapingResponse',
  full_name='ScrapingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='ScrapingResponse.page', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=142,
)

_SCRAPINGRESPONSE.fields_by_name['page'].message_type = _WEBPAGE
DESCRIPTOR.message_types_by_name['ScrapingRequest'] = _SCRAPINGREQUEST
DESCRIPTOR.message_types_by_name['WebPage'] = _WEBPAGE
DESCRIPTOR.message_types_by_name['ScrapingResponse'] = _SCRAPINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScrapingRequest = _reflection.GeneratedProtocolMessageType('ScrapingRequest', (_message.Message,), dict(
  DESCRIPTOR = _SCRAPINGREQUEST,
  __module__ = 'proto.scraping_pb2'
  # @@protoc_insertion_point(class_scope:ScrapingRequest)
  ))
_sym_db.RegisterMessage(ScrapingRequest)

WebPage = _reflection.GeneratedProtocolMessageType('WebPage', (_message.Message,), dict(
  DESCRIPTOR = _WEBPAGE,
  __module__ = 'proto.scraping_pb2'
  # @@protoc_insertion_point(class_scope:WebPage)
  ))
_sym_db.RegisterMessage(WebPage)

ScrapingResponse = _reflection.GeneratedProtocolMessageType('ScrapingResponse', (_message.Message,), dict(
  DESCRIPTOR = _SCRAPINGRESPONSE,
  __module__ = 'proto.scraping_pb2'
  # @@protoc_insertion_point(class_scope:ScrapingResponse)
  ))
_sym_db.RegisterMessage(ScrapingResponse)



_SCRAPER = _descriptor.ServiceDescriptor(
  name='Scraper',
  full_name='Scraper',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=144,
  serialized_end=204,
  methods=[
  _descriptor.MethodDescriptor(
    name='scrape',
    full_name='Scraper.scrape',
    index=0,
    containing_service=None,
    input_type=_SCRAPINGREQUEST,
    output_type=_SCRAPINGRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCRAPER)

DESCRIPTOR.services_by_name['Scraper'] = _SCRAPER

# @@protoc_insertion_point(module_scope)
